// autogenerated file

import * as grpc from 'grpc';
import { util } from 'protobufjs';
import Long = util.Long;
import * as events from 'events';

export interface FileOptions {
  lintSkip?: CommonLintSkip;
}

export interface MessageOptions {
  lintSkip?: CommonLintSkip;
}

export interface FieldOptions {
  /**
   * Used to declare which schema may have protobuf.Struct field.
   * TODO(skipor): if v1 and later apis use it move it to yandex.api package, and parse
   * at lint stage, but not at options parse.
   */
  oneOf?: string[];

  lintSkip?: CommonLintSkip;
}

export interface EnumOptions {
  lintSkip?: EnumLintSkip;
}

export interface EnumLintSkip {
  all?: boolean;

  valueNamesCase?: boolean;

  unspecifiedValue?: boolean;
}

export interface EnumValueOptions {
  lintSkip?: CommonLintSkip;
}

export interface ServiceOptions {
  lintSkip?: CommonLintSkip;

  skipGenerate?: boolean;
}

export interface MethodOptions {
  lintSkip?: CommonLintSkip;

  skipGenerate?: boolean;
}

export interface CommonLintSkip {
  all?: boolean;
}
