// autogenerated file

import * as grpc from 'grpc';
import { util } from 'protobufjs';
import Long = util.Long;
import * as events from 'events';

/**
 * Operation is annotation for rpc that returns longrunning operation, describes
 * message types that will be returned in metadata [google.protobuf.Any], and
 * in response [google.protobuf.Any] (for successful operation).
 */
export interface Operation {
  /**
   * Optional. If present, rpc returns operation which metadata field will
   * contains message of specified type.
   */
  metadata?: string;

  /**
   * Required. rpc returns operation, in case of success response will contains message of
   * specified field.
   */
  response?: string;
}
