// autogenerated file

import * as grpc from 'grpc';
import { util } from 'protobufjs';
import Long = util.Long;
import * as events from 'events';

export interface ApiEndpoint {
  id?: string;

  address?: string;
}

export class ApiEndpointService {
  constructor(address: string, credentials: grpc.ChannelCredentials, options?: object);
  get(request: GetApiEndpointRequest): Promise<ApiEndpoint>;

  list(request: ListApiEndpointsRequest): Promise<ListApiEndpointsResponse>;
}

export interface GetApiEndpointRequest {
  apiEndpointId?: string;
}

export interface ListApiEndpointsRequest {
  pageSize?: Long;

  pageToken?: string;
}

export interface ListApiEndpointsResponse {
  endpoints?: ApiEndpoint[];

  nextPageToken?: string;
}
