/* eslint-disable max-len */
type ServicesConfig = Record<string, Record<string, { importClassName: string; exportClassName?: string; }>>;

export const servicesConfig: ServicesConfig = {
    ai: {
        stt_v2_stt_service: { importClassName: 'SttServiceClient' },
        translate_v2_translation_service: { importClassName: 'TranslationServiceClient' },
        tts_v3_tts_service: { importClassName: 'SynthesizerClient' },
        vision_v1_vision_service: { importClassName: 'VisionServiceClient' },
        vision_v2_image_classifier_service: { importClassName: 'ImageClassifierServiceClient' },
        ocr_v1_ocr_service: { importClassName: 'TextRecognitionServiceClient' },
        assistants_v1_assistant_service: { importClassName: 'AssistantServiceClient' },
        assistants_v1_runs_run_service: { importClassName: 'RunServiceClient', exportClassName: 'AssistantRunServiceClient' },
        assistants_v1_threads_message_service: { importClassName: 'MessageServiceClient', exportClassName: 'AssistantMessageServiceClient' },
        assistants_v1_threads_thread_service: { importClassName: 'ThreadServiceClient', exportClassName: 'AssistantThreadServiceClient' },
    },
    apploadbalancer: {
        v1_backend_group_service: { importClassName: 'BackendGroupServiceClient' },
        v1_http_router_service: { importClassName: 'HttpRouterServiceClient' },
        v1_load_balancer_service: { importClassName: 'LoadBalancerServiceClient' },
        v1_target_group_service: { importClassName: 'TargetGroupServiceClient', exportClassName: 'AlbTargetGroupServiceClient' },
        v1_virtual_host_service: { importClassName: 'VirtualHostServiceClient' },
    },
    backup: {
        v1_backup_service: { importClassName: 'BackupServiceClient', exportClassName: 'BackupBackupServiceClient' },
        v1_policy_service: { importClassName: 'PolicyServiceClient', exportClassName: 'BackupPolicyServiceClient' },
        v1_provider_service: { importClassName: 'ProviderServiceClient', exportClassName: 'BackupProviderServiceClient' },
        v1_resource_service: { importClassName: 'ResourceServiceClient', exportClassName: 'BackupResourceServiceClient' },
    },
    billing: {
        v1_billing_account_service: { importClassName: 'BillingAccountServiceClient' },
        v1_budget_service: { importClassName: 'BudgetServiceClient' },
        v1_customer_service: { importClassName: 'CustomerServiceClient' },
        v1_service_service: { importClassName: 'ServiceServiceClient' },
        v1_sku_service: { importClassName: 'SkuServiceClient' },
    },
    cdn: {
        v1_cache_service: { importClassName: 'CacheServiceClient', exportClassName: 'CDNCacheServiceClient' },
        v1_origin_group_service: { importClassName: 'OriginGroupServiceClient', exportClassName: 'CDNOriginGroupServiceClient' },
        v1_origin_service: { importClassName: 'OriginServiceClient', exportClassName: 'CDNOriginServiceClient' },
        v1_provider_service: { importClassName: 'ProviderServiceClient', exportClassName: 'CDNProviderServiceClient' },
        v1_raw_logs_service: { importClassName: 'RawLogsServiceClient', exportClassName: 'CDNRawLogsServiceClient' },
        v1_resource_service: { importClassName: 'ResourceServiceClient', exportClassName: 'CDNResourceServiceClient' },
    },
    certificatemanager: {
        v1_certificate_content_service: { importClassName: 'CertificateContentServiceClient' },
        v1_certificate_service: { importClassName: 'CertificateServiceClient' },
    },
    compute: {
        v1_disk_placement_group_service: { importClassName: 'DiskPlacementGroupServiceClient' },
        v1_disk_service: { importClassName: 'DiskServiceClient' },
        v1_disk_type_service: { importClassName: 'DiskTypeServiceClient' },
        v1_filesystem_service: { importClassName: 'FilesystemServiceClient' },
        v1_host_group_service: { importClassName: 'HostGroupServiceClient' },
        v1_host_type_service: { importClassName: 'HostTypeServiceClient' },
        v1_image_service: { importClassName: 'ImageServiceClient', exportClassName: 'ComputeImageServiceClient' },
        v1_instance_service: { importClassName: 'InstanceServiceClient' },
        v1_placement_group_service: { importClassName: 'PlacementGroupServiceClient' },
        v1_snapshot_service: { importClassName: 'SnapshotServiceClient' },
        v1_zone_service: { importClassName: 'ZoneServiceClient' },
        v1_instancegroup_instance_group_service: { importClassName: 'InstanceGroupServiceClient' },
        v1_snapshot_schedule_service: { importClassName: 'SnapshotScheduleServiceClient' },
        v1_gpu_cluster_service: { importClassName: 'GpuClusterServiceClient' },
    },
    containerregistry: {
        v1_image_service: { importClassName: 'ImageServiceClient', exportClassName: 'CrImageServiceClient' },
        v1_lifecycle_policy_service: { importClassName: 'LifecyclePolicyServiceClient' },
        v1_registry_service: { importClassName: 'RegistryServiceClient' },
        v1_repository_service: { importClassName: 'RepositoryServiceClient' },
        v1_scanner_service: { importClassName: 'ScannerServiceClient' },
        v1_scan_policy_service: { importClassName: 'ScanPolicyServiceClient' },
    },
    dataproc: {
        v1_cluster_service: { importClassName: 'ClusterServiceClient', exportClassName: 'DataProcClusterServiceClient' },
        v1_job_service: { importClassName: 'JobServiceClient' },
        v1_resource_preset_service: { importClassName: 'ResourcePresetServiceClient' },
        v1_subcluster_service: { importClassName: 'SubclusterServiceClient' },
        manager_v1_job_service: { importClassName: 'JobServiceClient', exportClassName: 'ManagerJobServiceClient' },
        manager_v1_manager_service: { importClassName: 'DataprocManagerServiceClient' },
    },
    datasphere: {
        v1_app_token_service: { importClassName: 'AppTokenServiceClient' },
        v1_folder_budget_service: { importClassName: 'FolderBudgetServiceClient' },
        v1_node_service: { importClassName: 'NodeServiceClient' },
        v1_project_data_service: { importClassName: 'ProjectDataServiceClient' },
        v1_project_service: { importClassName: 'ProjectServiceClient' },
        v2_community_service: { importClassName: 'CommunityServiceClient' },
    },
    datatransfer: {
        v1_endpoint_service: { importClassName: 'EndpointServiceClient' },
        v1_transfer_service: { importClassName: 'TransferServiceClient' },
    },
    dns: { v1_dns_zone_service: { importClassName: 'DnsZoneServiceClient' } },
    iam: {
        v1_api_key_service: { importClassName: 'ApiKeyServiceClient' },
        v1_iam_token_service: { importClassName: 'IamTokenServiceClient' },
        v1_key_service: { importClassName: 'KeyServiceClient' },
        v1_role_service: { importClassName: 'RoleServiceClient' },
        v1_service_account_service: { importClassName: 'ServiceAccountServiceClient' },
        v1_user_account_service: { importClassName: 'UserAccountServiceClient' },
        v1_yandex_passport_user_account_service: { importClassName: 'YandexPassportUserAccountServiceClient' },
        v1_awscompatibility_access_key_service: { importClassName: 'AccessKeyServiceClient' },
    },
    iot: {
        broker_v1_broker_data_service: { importClassName: 'BrokerDataServiceClient' },
        broker_v1_broker_service: { importClassName: 'BrokerServiceClient' },
        devices_v1_device_data_service: { importClassName: 'DeviceDataServiceClient' },
        devices_v1_device_service: { importClassName: 'DeviceServiceClient' },
        devices_v1_registry_data_service: { importClassName: 'RegistryDataServiceClient' },
        devices_v1_registry_service: { importClassName: 'RegistryServiceClient', exportClassName: 'IotRegistryServiceClient' },
    },
    k8s: {
        v1_cluster_service: { importClassName: 'ClusterServiceClient', exportClassName: 'K8sClusterServiceClient' },
        v1_node_group_service: { importClassName: 'NodeGroupServiceClient' },
        v1_version_service: { importClassName: 'VersionServiceClient' },
    },
    kms: {
        v1_symmetric_crypto_service: { importClassName: 'SymmetricCryptoServiceClient' },
        v1_symmetric_key_service: { importClassName: 'SymmetricKeyServiceClient' },
        v1_asymmetricencryption_asymmetric_encryption_crypto_service: { importClassName: 'AsymmetricEncryptionCryptoServiceClient' },
        v1_asymmetricencryption_asymmetric_encryption_key_service: { importClassName: 'AsymmetricEncryptionKeyServiceClient' },
        v1_asymmetricsignature_asymmetric_signature_crypto_service: { importClassName: 'AsymmetricSignatureCryptoServiceClient' },
        v1_asymmetricsignature_asymmetric_signature_key_service: { importClassName: 'AsymmetricSignatureKeyServiceClient' },

    },
    loadtesting: {
        agent_v1_agent_registration_service: { importClassName: 'AgentRegistrationServiceClient', exportClassName: 'LoadTestingAgentRegistrationServiceClient' },
        agent_v1_agent_service: { importClassName: 'AgentServiceClient', exportClassName: 'LoadTestingAgentServiceClient' },
        agent_v1_job_service: { importClassName: 'JobServiceClient', exportClassName: 'LoadTestingJobServiceClient' },
        agent_v1_monitoring_service: { importClassName: 'MonitoringServiceClient', exportClassName: 'LoadTestingMonitoringServiceClient' },
        agent_v1_test_service: { importClassName: 'TestServiceClient', exportClassName: 'LoadTestingTestServiceClient' },
        agent_v1_trail_service: { importClassName: 'TrailServiceClient', exportClassName: 'LoadTestingTrailServiceClient' },
        api_v1_agent_service: { importClassName: 'AgentServiceClient', exportClassName: 'LoadTestingApiAgentServiceClient' },
    },
    loadbalancer: {
        v1_network_load_balancer_service: { importClassName: 'NetworkLoadBalancerServiceClient' },
        v1_target_group_service: { importClassName: 'TargetGroupServiceClient' },
    },
    lockbox: {
        v1_payload_service: { importClassName: 'PayloadServiceClient' },
        v1_secret_service: { importClassName: 'SecretServiceClient' },
    },
    logging: {
        v1_log_group_service: { importClassName: 'LogGroupServiceClient' },
        v1_log_ingestion_service: { importClassName: 'LogIngestionServiceClient' },
        v1_log_reading_service: { importClassName: 'LogReadingServiceClient' },
        v1_export_service: { importClassName: 'ExportServiceClient' },
        v1_sink_service: { importClassName: 'SinkServiceClient' },
    },
    marketplace: {
        metering_v1_image_product_usage_service: { importClassName: 'ImageProductUsageServiceClient', exportClassName: 'MarketplaceImageProductUsageServiceClient' },
        licensemanager_v1_instance_service: { importClassName: 'InstanceServiceClient', exportClassName: 'MarketplaceInstanceServiceClient' },
        licensemanager_v1_lock_service: { importClassName: 'LockServiceClient', exportClassName: 'MarketplaceLockServiceClient' },
        v1_metering_image_product_usage_service: { importClassName: 'ImageProductUsageServiceClient', exportClassName: 'MarketplaceMeteringImageProductUsageServiceClient' },
    },
    mdb: {
        clickhouse_v1_backup_service: { importClassName: 'BackupServiceClient', exportClassName: 'ClickHouseBackupServiceClient' },
        clickhouse_v1_cluster_service: { importClassName: 'ClusterServiceClient', exportClassName: 'ClickHouseClusterServiceClient' },
        clickhouse_v1_database_service: { importClassName: 'DatabaseServiceClient' },
        clickhouse_v1_format_schema_service: { importClassName: 'FormatSchemaServiceClient' },
        clickhouse_v1_ml_model_service: { importClassName: 'MlModelServiceClient' },
        clickhouse_v1_resource_preset_service: { importClassName: 'ResourcePresetServiceClient', exportClassName: 'ClickHouseResourcePresetServiceClient' },
        clickhouse_v1_user_service: { importClassName: 'UserServiceClient', exportClassName: 'ClickHouseUserServiceClient' },
        clickhouse_v1_versions_service: { importClassName: 'VersionsServiceClient' },
        elasticsearch_v1_auth_service: { importClassName: 'AuthServiceClient' },
        elasticsearch_v1_backup_service: { importClassName: 'BackupServiceClient', exportClassName: 'ElasticBackupServiceClient' },
        elasticsearch_v1_extension_service: { importClassName: 'ExtensionServiceClient', exportClassName: 'ElasticExtensionServiceClient' },
        elasticsearch_v1_cluster_service: { importClassName: 'ClusterServiceClient', exportClassName: 'ElasticClusterServiceClient' },
        elasticsearch_v1_resource_preset_service: { importClassName: 'ResourcePresetServiceClient', exportClassName: 'ElasticResourcePresetServiceClient' },
        elasticsearch_v1_user_service: { importClassName: 'UserServiceClient', exportClassName: 'ElasticUserServiceClient' },
        greenplum_v1_cluster_service: { importClassName: 'ClusterServiceClient', exportClassName: 'GreenplumClusterServiceClient' },
        greenplum_v1_backup_service: { importClassName: 'BackupServiceClient', exportClassName: 'GreenplumBackupServiceClient' },
        greenplum_v1_resource_preset_service: { importClassName: 'ResourcePresetServiceClient', exportClassName: 'GreenplumResourcePresetServiceClient' },
        kafka_v1_cluster_service: { importClassName: 'ClusterServiceClient', exportClassName: 'KafkaClusterServiceClient' },
        kafka_v1_connector_service: { importClassName: 'ConnectorServiceClient' },
        kafka_v1_resource_preset_service: { importClassName: 'ResourcePresetServiceClient', exportClassName: 'KafkaResourcePresetServiceClient' },
        kafka_v1_topic_service: { importClassName: 'TopicServiceClient' },
        kafka_v1_user_service: { importClassName: 'UserServiceClient', exportClassName: 'KafkaUserServiceClient' },
        mongodb_v1_backup_service: { importClassName: 'BackupServiceClient', exportClassName: 'MongoBackupServiceClient' },
        mongodb_v1_cluster_service: { importClassName: 'ClusterServiceClient', exportClassName: 'MongoClusterServiceClient' },
        mongodb_v1_database_service: { importClassName: 'DatabaseServiceClient', exportClassName: 'MongoDatabaseServiceClient' },
        mongodb_v1_resource_preset_service: { importClassName: 'ResourcePresetServiceClient', exportClassName: 'MongoResourcePresetServiceClient' },
        mongodb_v1_user_service: { importClassName: 'UserServiceClient', exportClassName: 'MongoUserServiceClient' },
        mysql_v1_backup_service: { importClassName: 'BackupServiceClient', exportClassName: 'MysqlBackupServiceClient' },
        mysql_v1_cluster_service: { importClassName: 'ClusterServiceClient', exportClassName: 'MysqlClusterServiceClient' },
        mysql_v1_database_service: { importClassName: 'DatabaseServiceClient', exportClassName: 'MysqlDatabaseServiceClient' },
        mysql_v1_resource_preset_service: { importClassName: 'ResourcePresetServiceClient', exportClassName: 'MysqlResourcePresetServiceClient' },
        mysql_v1_user_service: { importClassName: 'UserServiceClient', exportClassName: 'MysqlUserServiceClient' },
        opensearch_v1_backup_service: { importClassName: 'BackupServiceClient', exportClassName: 'OpenSearchBackupServiceClient' },
        opensearch_v1_cluster_service: { importClassName: 'ClusterServiceClient', exportClassName: 'OpenSearchClusterServiceClient' },
        opensearch_v1_resource_preset_service: { importClassName: 'ResourcePresetServiceClient', exportClassName: 'OpenSearchResourcePresetServiceClient' },
        postgresql_v1_backup_service: { importClassName: 'BackupServiceClient', exportClassName: 'PgsqlBackupServiceClient' },
        postgresql_v1_cluster_service: { importClassName: 'ClusterServiceClient', exportClassName: 'PgsqlClusterServiceClient' },
        postgresql_v1_database_service: { importClassName: 'DatabaseServiceClient', exportClassName: 'PgsqlDatabaseServiceClient' },
        postgresql_v1_resource_preset_service: { importClassName: 'ResourcePresetServiceClient', exportClassName: 'PgsqlResourcePresetServiceClient' },
        postgresql_v1_user_service: { importClassName: 'UserServiceClient', exportClassName: 'PgsqlUserServiceClient' },
        postgresql_v1_perf_diag_service: { importClassName: 'PerformanceDiagnosticsServiceClient', exportClassName: 'PgsqlPerformanceDiagnosticsServiceClient' },
        redis_v1_backup_service: { importClassName: 'BackupServiceClient', exportClassName: 'RedisBackupServiceClient' },
        redis_v1_cluster_service: { importClassName: 'ClusterServiceClient', exportClassName: 'RedisClusterServiceClient' },
        redis_v1_resource_preset_service: { importClassName: 'ResourcePresetServiceClient', exportClassName: 'RedisResourcePresetServiceClient' },
        sqlserver_v1_backup_service: { importClassName: 'BackupServiceClient', exportClassName: 'SqlServerBackupServiceClient' },
        sqlserver_v1_cluster_service: { importClassName: 'ClusterServiceClient', exportClassName: 'SqlServerClusterServiceClient' },
        sqlserver_v1_database_service: { importClassName: 'DatabaseServiceClient', exportClassName: 'SqlServerDatabaseServiceClient' },
        sqlserver_v1_resource_preset_service: { importClassName: 'ResourcePresetServiceClient', exportClassName: 'SqlServerResourcePresetServiceClient' },
        sqlserver_v1_user_service: { importClassName: 'UserServiceClient', exportClassName: 'SqlServerUserServiceClient' },
    },
    monitoring: {
        v3_dashboard_service: { importClassName: 'DashboardServiceClient' },
    },
    operation: {
        operation_service: { importClassName: 'OperationServiceClient' },
    },
    organizationmanager: {
        v1_group_service: { importClassName: 'GroupServiceClient' },
        v1_organization_service: { importClassName: 'OrganizationServiceClient' },
        v1_user_service: { importClassName: 'UserServiceClient' },
        v1_saml_certificate_service: { importClassName: 'CertificateServiceClient', exportClassName: 'OmCertificateServiceClient' },
        v1_saml_federation_service: { importClassName: 'FederationServiceClient' },
        v1_group_mapping_service: { importClassName: 'GroupMappingServiceClient' },
        v1_ssh_certificate_service: { importClassName: 'SshCertificateServiceClient' },
    },
    resourcemanager: {
        v1_cloud_service: { importClassName: 'CloudServiceClient' },
        v1_folder_service: { importClassName: 'FolderServiceClient' },
    },
    serverless: {
        apigateway_v1_apigateway_service: { importClassName: 'ApiGatewayServiceClient' },
        containers_v1_container_service: { importClassName: 'ContainerServiceClient' },
        functions_v1_function_service: { importClassName: 'FunctionServiceClient' },
        mdbproxy_v1_proxy_service: { importClassName: 'ProxyServiceClient' },
        triggers_v1_trigger_service: { importClassName: 'TriggerServiceClient' },
        apigateway_websocket_v1_connection_service: { importClassName: 'ConnectionServiceClient', exportClassName: 'WebSocketConnectionServiceClient' },
    },
    storage: {
        v1_bucket_service: { importClassName: 'BucketServiceClient' },
    },
    vpc: {
        v1_address_service: { importClassName: 'AddressServiceClient' },
        v1_network_service: { importClassName: 'NetworkServiceClient' },
        v1_route_table_service: { importClassName: 'RouteTableServiceClient' },
        v1_security_group_service: { importClassName: 'SecurityGroupServiceClient' },
        v1_subnet_service: { importClassName: 'SubnetServiceClient' },
        v1_gateway_service: { importClassName: 'GatewayServiceClient' },
    },
    ydb: {
        v1_backup_service: { importClassName: 'BackupServiceClient', exportClassName: 'YdbBackupServiceClient' },
        v1_database_service: { importClassName: 'DatabaseServiceClient', exportClassName: 'YdbDatabaseServiceClient' },
        v1_location_service: { importClassName: 'LocationServiceClient' },
        v1_resource_preset_service: { importClassName: 'ResourcePresetServiceClient', exportClassName: 'YdbResourcePresetServiceClient' },
        v1_storage_type_service: { importClassName: 'StorageTypeServiceClient' },
    },
};
