export const INITIALIZE_MAX_ATTEMPTS_OF_GET_TOKEN = 5;

export const INITIALIZE_BACKOFF_SLOT_DURATION = 5; // ms

export const INITIALIZE_BACKOFF_CEILING = 3; // up to 5 * (2 ** 3) = 40 ms

export const INITIALIZE_BACKOFF_UNCERTAIN_RATIO = 0.5;

export const GET_TOKEN_BACKOFF_SLOT_DURATION = 1 * 30 * 1000; // every 30 mins

export const GET_TOKEN_BACKOFF_CEILING = 1; // up to 30 * (2 ** 1) = 60 min

export const GET_TOKEN_BACKOFF_UNCERTAIN_RATIO = 0.3;

export const TOKEN_MINIMUM_LIFETIME_MARGIN_MS = 15 * 60 * 1000;

export const TOKEN_LIFETIME_LEFT_TO_REFRESH_PCT = 90;

export const TOKEN_LIFETIME_LEFT_TO_REPORT_ERROR_PCT = 80;

export const ERROR_REPORT_INTERVAL_MS = 1 * 60 * 1000;
